package com.listore.dao;

import java.util.List;

import com.listore.commen.ServerResponse;
import com.listore.pojo.Category;

public interface CategoryMapper {
	/*
	 * 检查品类名是否存在
	 * */
	int checkName(String name);
	/*
	 * 
	 * 通过品类的名字获取品类的详细信息
	 * 
	 * */
	Category selectByName(String name);
	/*
	 * 通过pid获得子节点
	 * */
	ServerResponse<List<Category>> selectCategoriesByPid(int pid);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    int insert(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    /*
     * 检查插入的Category对象是否在数据库中已经存在
     * */
    int check_add_Category(String name);
    int insertSelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    Category selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Category record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table listore_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Category record);
}